-- TABLE DROP SCRIPTS
/*IF OBJECT_ID (N'Tag', N'U') IS NOT NULL
BEGIN
	DROP TABLE dbo.Tag
END
IF OBJECT_ID (N'TagDetail', N'U') IS NOT NULL
BEGIN
	DROP TABLE dbo.TagDetail
END
*/
-- CREATE TABLE SCRIPTS
IF OBJECT_ID (N'Tag', N'U') IS NULL
BEGIN
	CREATE TABLE dbo.Tag
(
	Id INT NOT NULL CONSTRAINT PK_Tag PRIMARY KEY (Id) IDENTITY (1,1),
	AdminUserId INT NOT NULL CONSTRAINT FK_Tag_UserAccount FOREIGN KEY (AdminUserId) REFERENCES dbo.UserAccount(Id),
	[Name] VARCHAR(100) NOT NULL,
	Active BIT NOT NULL CONSTRAINT DK_Tag_Active DEFAULT 0,
	[Type] INT NOT NULL  CONSTRAINT DK_Tag_Type DEFAULT 0,
	CreatedOn DATETIME NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL,
	ModifiedOn DATETIME NULL,
	ModifiedBy VARCHAR(50) NULL
)
END

ALTER TABLE dbo.Tag Add [Type] INT NOT NULL  CONSTRAINT DK_Tag_Type DEFAULT 0
IF OBJECT_ID (N'TagDetail', N'U') IS NULL
BEGIN
	CREATE TABLE dbo.TagDetail
(
	Id INT NOT NULL CONSTRAINT PK_TagDetail PRIMARY KEY (Id) IDENTITY (1,1),
	TagId INT NOT NULL CONSTRAINT FK_TagDetail_Tag FOREIGN KEY (TagId) REFERENCES dbo.Tag(Id),
	UserId INT NOT NULL CONSTRAINT FK_TagDetail_UserAccount FOREIGN KEY (UserId) REFERENCES dbo.UserAccount(Id),	
	Active BIT NOT NULL  CONSTRAINT DK_TagDetail_Active DEFAULT 0,
	CreatedOn DATETIME NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL,
	ModifiedOn DATETIME NULL,
	ModifiedBy VARCHAR(50) NULL
)
END

Select * from Tag
Select * from TagDetail
Select * from UserAccount